apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cloudapp
  labels:
    app: cloudapp
spec:
  replicas: 4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
       containers: 
       - name: cloudapp
         image: mikaelaolsson/cloudapp:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudapp
  name: cloudapp
  namespace: default
spec:
  clusterIP: 10.107.113.156
  clusterIPs:
  - 10.107.113.156
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30610
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cloudapp
  sessionAffinity: None
  type: NodePort 
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 namespace: default
 name: cloudapp
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: cloudapp
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50