apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cloudapp
  labels:
    app: cloudapp
spec:
  replicas: 4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: cloudapp
  template:
    metadata:
      labels:
        app: cloudapp
    spec:
       containers: 
       - name: cloudapp
         image: mikaelaolsson/cloudapp:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name:  cloud-service
spec:
  selector:
    app:  cloudapp
  type:  NodePort
  ports:
  - name:  http
    port:  80
    targetPort:  80 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cloudapp
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 25
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudapp