name: Docker Image CI

on:
  push:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Genomför unit-tester
       run: dotnet test
        
     - name: Loggar in på Docker
       uses: docker/login-action@v1
       with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
            
     - name: Building the Docker Image
       uses: docker/build-push-action@v2.9.0
       with:
          push: true
          tags: mikaelaolsson/cloudapp:dev
